config/routes.rb
Rails.application.routes.draw do
  resources :points, except: [:show, :new] do
    resources :triggers, only: [:destroy]
    get 'search', on: :collection
  end
  resources :categories do
    post 'sort', on: :collection
  end
  resources :markers, only: :index
  resources :reports, only: :index
  resources :descriptions, only: :index

  root 'points#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :points, through: :markers
  has_many :markers

  enum color: [:blue, :cyan, :green, :orange, :purple, :red, :yellow]

  validates_presence_of :name, :color

  acts_as_list top_of_list: 0

  def to_s
    name
  end

  def as_json(*)
    {name: name}
  end
end

app/models/marker.rb
class Marker < ActiveRecord::Base
  belongs_to :point
  belongs_to :category

  def as_json(*)
    {category: category.name, point: point.title}
  end
end

app/models/point.rb
class Point < ActiveRecord::Base
  has_many :categories, through: :markers
  has_many :markers, dependent: :destroy
  has_many :triggers

  validates_presence_of :title, :categories, :latitude, :longitude

  accepts_nested_attributes_for :triggers, reject_if: :all_blank, allow_destroy: true

  default_scope { order(:title) }

  def self.duplicates
    Point.group(:title).count.select { |_, count| count > 1 }.keys
  end

  def self.words_count
    text = Point.all.map(&:description).join
    WordsCounted.count(text).token_count
  end

  def inline_categories
    categories.join(", ")
  end

  def to_s
    title
  end

  def color
    categories.first.color
  end

  def as_json(*)
    json = {title: title, latitude: latitude, longitude: longitude, audio: audio, color: color}
    json[:triggers] = if triggers.present?
      triggers.map.with_index(1) do |trigger, index|
        {id: "#{audio}-#{index}", latitude: trigger.latitude, longitude: trigger.longitude}
      end
    else
      [{id: "#{audio}-1", latitude: latitude, longitude: longitude}]
    end
    json
  end
end

app/models/trigger.rb
class Trigger < ActiveRecord::Base
  belongs_to :point

  validates_presence_of :latitude, :longitude
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  http_basic_authenticate_with(
    name: ENV["HTTP_BASIC_AUTH_NAME"],
    password: ENV["HTTP_BASIC_AUTH_PASSWORD"]
  ) if Rails.env.production?
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.order(:position)

    respond_to do |f|
      f.html
      f.json { render json: @categories }
    end
  end

  def show
    category
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, notice: %(Category "#{@category}" created)
    else
      render :new
    end
  end

  def edit
    category
  end

  def update
    if category.update(category_params)
      redirect_to categories_path, notice: %(Category "#{category}" updated)
    else
      render :edit
    end
  end

  def destroy
    category.destroy
    redirect_to categories_path, alert: %(Category "#{category}" removed)
  end

  def sort
    params.permit(:id, :position)
    category = Category.find(params[:id])
    category.insert_at(params[:position].to_i)
    head :ok
  end

  private

  def category_params
    params.require(:category).permit(:name, :color)
  end

  def category
    @category ||= Category.find(params[:id])
  end
end

app/controllers/descriptions_controller.rb
class DescriptionsController < ApplicationController
  def index
    @points = Point.all
  end
end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  def index
    @markers = Marker.all

    respond_to do |f|
      f.json { render json: @markers }
    end
  end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  def index
    @point = Point.new
    points
    categories

    respond_to do |f|
      f.html
      f.json { render json: @points }
    end
  end

  def edit
    point
    categories
  end

  def create
    @point = Point.new(point_params)
    @point.audio = params[:point][:title].parameterize
    points
    if @point.save
      redirect_to edit_point_path(@point), notice: %(Point created)
    else
      render :index
    end
  end

  def update
    if point.update(point_params)
      redirect_to edit_point_path(point), notice: %(Point "#{point}" updated)
    else
      render :edit
    end
  end

  def destroy
    point.destroy
    redirect_to root_path, alert: %(Point "#{point}" removed)
  end

  def search
    @search_results = Point.where("title ILIKE ?", "%#{params[:term]}%")
  end

  private

  def point_params
    params.require(:point).permit(
      :title,
      :latitude,
      :longitude,
      :audio,
      :description,
      category_ids: [],
      triggers_attributes: [:id, :latitude, :longitude, :_destroy]
    )
  end

  def categories
    @categories = Category.order(:position)
  end

  def point
    @point ||= Point.find(params[:id])
  end

  def points
    @points ||= Point.includes(:categories)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @duplicates = Point.includes(:categories).where(title: Point.duplicates)
    @without_description = Point.includes(:categories).where("description is NULL OR description = ''")
  end
end

app/controllers/triggers_controller.rb
class TriggersController < ApplicationController
  def destroy
    trigger = Trigger.find(params[:id])
    trigger.destroy
    redirect_to edit_point_path(params[:point_id]), alert: "Trigger removed"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.erb
<%= form_for @category, html: { class: "form-stacked" } do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :color %>
  <%= f.select :color, Category.colors.keys.to_a, selected: @category.color %>

  <div>
    <%= f.button "Confirm", class: "btn btn-positive" %>
  </div>
<% end %>

<%= link_to "< Back", categories_path %>

app/views/categories/edit.erb
<%= render "form" %>

app/views/categories/index.erb
<table class="table-hover">
  <colgroup>
    <col class="3/4"></col>
    <col class="1/4"></col>
  </colgroup>
  <thead>
    <tr>
      <th>Categories</th>
      <th></th>
    </tr>
  </thead>
  <tbody class="js-sortable" data-sortable-url="<%= sort_categories_path %>">
    <%- @categories.each do |category| %>
      <tr data-id="<%= category.id %>">
        <td>
          <small class="text-muted js-sortable-handle">⇅</small>
          <div class="dot" style="background-color: <%= category.color %>;"></div>
          <%= link_to category, category %> (<%= category.points.count %>)
        </td>
        <td class="text-right">
          <ul class="list-divided padding-quarter-top">
            <li>
              <%= link_to "Edit", edit_category_path(category) %>
            </li>
            <li>
              <%= link_to "Remove",
                    category_path(category),
                    method: :delete,
                    class: "text-red",
                    data: {
                      confirm: "This will remove: #{category}. Are you sure?"
                    }
              %>
            </li>
          </ul>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td class="padding-top">
        <ul class="list-divided">
          <li><%= link_to "< Back", root_path %></li>
          <li><%= link_to "Add a new category", new_category_path, class: "text-green" %></li>
        </ul>
      </td>
    </tr>
  <tfoot>
</table>

app/views/categories/new.erb
<%= render "form" %>

app/views/categories/show.erb
<table class="table-hover">
  <thead>
    <tr>
      <th><%= @category %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%- @category.points.each do |point| %>
      <tr>
        <td><%= link_to point, edit_point_path(point) %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td class="padding-top">
        <%= link_to "< Back", categories_path %>
      </td>
    </tr>
  <tfoot>
</table>

app/views/descriptions/index.erb
<%- @points.each_with_index do |point, index| %>
  <div class="margin-top">
    <%= index + 1 %>. <%= link_to point.title, edit_point_path(point) %>
  </div>

  <%= point.description %>

  <div>
    <%= text_field_tag nil, point.audio, class: "js-select-text-field" %>
  </div>
<% end %>

<script>
  $('.js-select-text-field').click(function() { $(this).select(); });
</script>

app/views/layouts/application.erb
<!DOCTYPE html>
<html>
<head>
  <title>Echotags Marker</title>
  <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar">
  <div class="container">
    <div class="grid grid-pair">
      <div class="grid-item 1/2">
        <ul class="navbar-menu">
          <li class="padding-right">
            <%= link_to_unless_current "Map", root_path, class: "no-padding-sides" %>
          </li>
          <li class="padding-right">
            <%= link_to_unless_current "Data", categories_path, class: "no-padding-sides" %>
          </li>
          <li class="padding-right">
            <%= link_to_unless_current "Reports", reports_path, class: "no-padding-sides" %>
          </li>
          <li class="padding-right">
            <%= link_to_unless_current "Descriptions", descriptions_path, class: "no-padding-sides" %>
          </li>
        </ul>
      </div>
      <div class="grid-item 1/2">
        <%= form_tag search_points_path, method: :get, class: "form-inline" do |f| %>
          <%= search_field_tag :term, nil, placeholder: "Search point.." %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <%- flash.presence&.each do |type, content| %>
    <div class="box box-<%= type %>"><%= content %></div>
  <% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/points/_form.erb
<%= form_for @point, html: { class: "form-stacked" } do |f| %>
  <%- if errors = @point.errors.presence %>
    <div class="box box-negative margin-bottom">
      <ul>
        <%- errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title, class: "1/1" %>

  <%= f.label :category_ids, "Categories" %>
  <%= f.select :category_ids,
        options_from_collection_for_select(@categories, :id, :name, @point.category_ids),
        { include_blank: false },
        { multiple: true, class: "js-chosen" }
  %>

  <%= f.label :position, "Position" %>
  <div class="grid margin-bottom">
    <div class="grid-item 1/2">
      <%= f.text_field :latitude, class: "1/1 js-coordinates"  %>
      <small class="text-muted">Latitude</small>
    </div>
    <div class="grid-item 1/2">
      <%= f.text_field :longitude, class: "1/1" %>
      <small class="text-muted">Longitude</small>
    </div>
  </div>

  <%= f.label :description %>
  <%= f.text_area :description, rows: 7, class: "1/1" %>

  <%- unless current_page?(root_path) %>
    <%= f.label :audio %>
    <%= f.text_field :audio, class: "1/1" %>
  <% end %>

  <div class="margin-quarter-bottom">Triggers</div>

  <ol>
  <%- @point.triggers.each do |trigger| %>
    <li>
      <div class="grid grid-pair grid-middle">
        <div class="grid-item 1/2 text-mono">
          <%= trigger.latitude %>, <%= trigger.longitude %>
        </div>
        <div class="grid-item 1/2">
          <%= link_to "Remove", point_trigger_path(@point, trigger), method: :delete, class: "text-red" %>
        </div>
    </li>
  <% end %>
    <li><%= link_to_add_association 'Add trigger', f, :triggers %></li>
  </ol>

  <%= f.button "Confirm", class: "btn btn-positive" %>
<% end %>

app/views/points/_trigger_fields.erb
<li class="margin-top">
  <div class="grid grid-middle margin-bottom">
    <div class="grid-item 1/2">
      <%= f.text_field :latitude, class: "1/1 js-coordinates"  %>
      <small class="text-muted">Latitude</small>
    </div>
    <div class="grid-item 1/2">
      <%= f.text_field :longitude, class: "1/1" %>
      <small class="text-muted">Longitude</small>
    </div>
  </div>
</li>

app/views/points/edit.erb
<div class="grid">
  <div class="grid-item 1/2">
    <div class="grid grid-middle grid-pair">
      <div class="grid-item 1/2">
        <h4 class="no-margin-top">Edit point</h4>
      </div>
      <div class="grid-item 1/2">
        <%= link_to "Remove",
              point_path(@point),
              method: :delete,
              class: "block text-red margin-bottom text-right",
              data: { confirm: "This will remove: #{@point}. Are you sure?" }
        %>
      </div>
    </div>

    <%= render "form" %>
  </div>
  <div class="grid-item 1/2">
    <%= render "points/edit/map" %>
  </div>
</div>

app/views/points/edit/_map.erb
<div id="map" class="map"></div>
<script>
    var map, marker, labelIndex = 1;

    window.initMap = function() {
      var position = new google.maps.LatLng(<%= @point.latitude %>, <%= @point.longitude %>);

      map = new google.maps.Map(document.getElementById('map'), {
        center: position,
        zoom: 15,
        streetViewControl: false
      });

      marker = new google.maps.Marker({
        map: map,
        position: position,
        draggable: true,
        icon: pinSymbol("<%= @point.color %>")
      });
      marker.addListener('drag', updatePosition);

      <%- @point.triggers.each do |trigger| %>
        var position = new google.maps.LatLng(<%= trigger.latitude %>, <%= trigger.longitude %>);

        var marker = new google.maps.Marker({
          map: map,
          position: position,
          path: google.maps.SymbolPath.CIRCLE,
          label: (labelIndex++).toString()
        });
      <% end %>
    }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCSi9XqJJg8XlhclU-Yx0Qs84_9T6-7BxA&callback=initMap"></script>

app/views/points/index.erb
<div class="grid">
  <div class="grid-item 1/3">
    <h4 class="no-margin-top">New point</h4>
    <%= render "form" %>
  </div>
  <div class="grid-item 2/3">
    <%= render "points/index/map" %>

    <ul class="list-divided text-muted text-right margin-half-top">
      <li>Total number of points: <%= @points.count %></li>
      <li>Words count: ~<%= @points.words_count %></li>
    </ul>
  </div>
</div>

app/views/points/index/_map.erb
<div id="map" class="map"></div>
<script>
    var map, infoWindow, newMarker, labelIndex = 1;

    window.initMap = function() {
      map = new google.maps.Map(document.getElementById('map'), {
        center: {lat: 52.371413, lng: 4.897451},
        zoom: 13,
        streetViewControl: false
      });

      map.addListener('click', function(event) {
        if (newMarker) { newMarker.setMap(null); }

        newMarker = new google.maps.Marker({
          map: map,
          draggable: true,
          position: event.latLng,
          icon: pinSymbol("#fff")
        });

        updatePositionOf(newMarker);
        newMarker.addListener('drag', updatePosition);
      });

      <%- @points.each do |point| %>
        var position = new google.maps.LatLng(<%= point.latitude %>, <%= point.longitude %>);

        var marker = new google.maps.Marker({
          map: map,
          position: position,
          icon: pinSymbol("<%= point.color %>")
        });

        infoWindow = new google.maps.InfoWindow();

        marker.addListener('click', function() {
          infoWindow.setContent('<div><strong><%= escape_javascript(point.title) %></strong></div>' +
            '<div class="margin-bottom"><%= point.inline_categories %></div>' +
            '<div class="margin-bottom"><%= escape_javascript(point.description) || "Missing description" %></div>' +
            '<div class="text-muted"><%= point.latitude %>, <%= point.longitude %></div>' +
            '<div><%= link_to("Edit point", edit_point_path(point)) %></div>'
          );
          infoWindow.open(map, this);
        });
      <% end %>
    }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCSi9XqJJg8XlhclU-Yx0Qs84_9T6-7BxA&callback=initMap"></script>

app/views/points/search.erb
<table class="table-hover">
  <colgroup>
    <col class="1/3"></col>
    <col class="2/3"></col>
  </colgroup>
  <thead>
    <tr>
      <th>Search results for "<%= params[:term] %>":</th>
    </tr>
  </thead>
  <tbody>
    <%- @search_results.each do |point| %>
      <tr>
        <td><%= link_to point, edit_point_path(point) %></td>
        <td class="text-muted text-small"><%= point.inline_categories %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reports/index.erb
<table class="table-hover">
  <colgroup>
    <col class="1/3"></col>
    <col class="1/3"></col>
    <col class="1/6"></col>
    <col class="1/6"></col>
  </colgroup>
  <thead>
    <tr>
      <th>Duplicated points (<%= @duplicates.count %>):</th>
    </tr>
  </thead>
  <tbody>
    <%- @duplicates.each do |point| %>
      <tr>
        <td><%= link_to point, edit_point_path(point) %></td>
        <td class="text-muted text-small"><%= point.inline_categories %></td>
        <td class="text-muted text-small"><%= point.latitude %></td>
        <td class="text-muted text-small"><%= point.longitude %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<table class="table-hover">
  <colgroup>
    <col class="1/3"></col>
    <col class="2/3"></col>
  </colgroup>
  <thead>
    <tr>
      <th>Points without description (<%= @without_description.count %>):</th>
    </tr>
  </thead>
  <tbody>
    <%- @without_description.each do |point| %>
      <tr>
        <td><%= link_to point, edit_point_path(point) %></td>
        <td class="text-muted text-small"><%= point.inline_categories %></td>
      </tr>
    <% end %>
  </tbody>
</table>